"use client";

import React, { useState } from "react";
import Breadcrumbs from "@/app/Components/Breadcrumbs/Breadcrumbs";
import {
  Waves,
  Activity,
  Cog,
  Atom,
  Fuel,
  Zap,
  Car,
  Plane,
  Wrench,
  FlaskConical,
  Plus,
  Minus,
} from "lucide-react";
import ProjectsHighlight from "@/app/Components/ProjectsHighlight/ProjectsHighlight";
import "./cfd.css";

const IMG = "/assets/images/industries/computational-fluid-dynamics-services";

type Point = { head?: string; body: string };

const services: {
  id: string;
  title: string;
  description: string;
  points: Point[];
  images?: { src: string; alt: string }[];
}[] = [
  {
    id: "cfd-fsi",
    title: "Computational Fluid Dynamics (CFD) & Fluid-Structure Interaction",
    description:
      "By utilizing focused fluid dynamics analyses, we model intricate fluid movements to fine-tune thermal systems and accurately forecast how fluids in motion affect nearby physical structures. To produce highly dependable virtual prototypes, our specialists rely on premium software tools, particularly leveraging the advanced capabilities of the ANSYS Fluent platform.",
    points: [
      {
        head: "Fluid-Structure Interaction (FSI)",
        body: "We examine the combined effects of fluid streams on component integrity — essential for assessing acoustic-induced and flow-induced vibrations, water hammer or surge conditions, and the impact of sudden valve closures within piping arrays.",
      },
      {
        head: "Multi-Phase & Free Surface Flows",
        body: "Our industry-recognized simulations accurately map liquid-gas boundaries, cavitation, slurry movement, and mixing processes across rotating equipment and process machinery.",
      },
      {
        head: "Thermal & Conjugate Heat Transfer (CHT)",
        body: "Focused thermal evaluations to track complicated heat loss and dissipation, including thermal stratification inside pipes and thermal shocks affecting pressure vessels and heat exchangers.",
      },
      {
        head: "Flow Optimization",
        body: "Our approaches reduce unnecessary pressure drops, clear out dead zones, and streamline fluid pathways throughout intricate valves, ducts, and manifold networks.",
      },
    ],
    images: [
      { src: `${IMG}/1.png`, alt: "CFD flow simulation result" },
      { src: `${IMG}/2.png`, alt: "Fluid-structure interaction analysis" },
    ],
  },
  {
    id: "damage-life",
    title: "Materials, Damage Modeling & Life Assessment",
    description:
      "Moving past basic linear evaluations, we investigate how severe mechanical and thermal stresses deteriorate materials throughout their operational lifespan. By integrating these insights with our fluid dynamics analyses, we seamlessly project complicated thermal data onto comprehensive structural frameworks.",
    points: [
      {
        head: "High-Temperature Durability",
        body: "We analyze fatigue, creep, and their combined interactions within high-pressure, high-temperature equipment. Typical assets evaluated include industrial reactors, steam turbines, and power plant piping assemblies.",
      },
      {
        head: "Fracture Mechanics & Fitness-for-Service (FFS)",
        body: "By modeling both the start and subsequent spread of structural cracks, we confidently estimate an asset's remaining useful life and establish secure operating boundaries.",
      },
    ],
    images: [
      { src: `${IMG}/3.png`, alt: "Thermal-structural damage model" },
      { src: `${IMG}/4.png`, alt: "Fracture mechanics crack growth model" },
    ],
  },
  {
    id: "mbd",
    title: "Multi-Body Dynamics (MBD)",
    description:
      "We determine the actual dynamic and kinematic responses of intricate, linked assemblies comprising both flexible and rigid parts. When paired with the robust outputs of our ANSYS Fluent workflows, these dynamic simulations effectively incorporate real-world forces generated by fluid motion.",
    points: [
      {
        head: "Dynamic Load Extraction",
        body: "We calculate accurate, fluctuating accelerations, velocities, and joint forces experienced throughout standard operating cycles.",
      },
      {
        head: "FEA Integration",
        body: "By transferring these precise dynamic forces directly into subsequent fatigue and structural models, we achieve unparalleled levels of physical accuracy.",
      },
    ],
    images: [{ src: `${IMG}/1.png`, alt: "Multi-body dynamics assembly simulation" }],
  },
  {
    id: "coupled-multiphysics",
    title: "Fully Coupled Multiphysics Analysis",
    description:
      "Because practical engineering challenges seldom occur in a vacuum, we connect separate physical disciplines using simultaneous, multi-directional coupling. This advanced approach is heavily supported by our foundational fluid dynamics capabilities.",
    points: [
      {
        head: "Electro-Magnetic-Thermal-Structural-Flow Coupling",
        body: "We model interconnected systems where electrical currents produce heat, which in turn alters cooling performance and triggers structural expansion. Typical applications include busbars, electrical transformers, and electric vehicle powertrains — where our comprehensive fluid simulations are essential for assessing and optimizing overall thermal management.",
      },
    ],
  },
];

const serviceIcons = [Waves, Activity, Cog, Atom];

const heroNav = [
  { title: "CFD & FSI", id: "cfd-fsi" },
  { title: "Damage & Life Assessment", id: "damage-life" },
  { title: "Multi-Body Dynamics", id: "mbd" },
  { title: "Coupled Multiphysics", id: "coupled-multiphysics" },
  { title: "Industries Served", id: "industries" },
];

const advantages = [
  {
    number: "01",
    title: "Cross-Domain Expertise",
    text: "Rather than simply delivering attractive visual plots, we convert fluid data into tangible structural outcomes — ensuring your vessels, piping, and pumps are fully capable of surviving harsh operational demands.",
  },
  {
    number: "02",
    title: "Root Cause Analysis",
    text: "We identify the precise origins of recurring equipment failures, from flow-induced cracking and localized cavitation to severe thermal fatigue, using advanced ANSYS Fluent techniques to correctly diagnose hidden fluid-related issues.",
  },
  {
    number: "03",
    title: "Code Compliance",
    text: "We seamlessly align our sophisticated simulation results with established international standards, including BS, API, and ASME, guaranteeing comprehensive design validation.",
  },
];

const industries = [
  {
    icon: Fuel,
    title: "Oil & Gas, Petrochemicals & Refineries",
    body: "Offshore platforms, subsea hardware, storage tanks, pressure vessels, and complicated piping infrastructure.",
  },
  {
    icon: Zap,
    title: "Power Generation (Thermal, Nuclear, Renewables)",
    body: "High-energy piping, heat exchangers, gas and steam turbines, and boiler headers.",
  },
  {
    icon: Car,
    title: "Automotive & Electric Vehicles (EV)",
    body: "Structural resilience, motor cooling mechanisms, battery thermal management, and overall powertrain dynamics.",
  },
  {
    icon: Plane,
    title: "Aerospace & Defense",
    body: "High-velocity impacts, defense payloads, turbomachinery, and specialized aerodynamic components.",
  },
  {
    icon: Wrench,
    title: "Heavy Engineering & Industrial Machinery",
    body: "Heavy cranes, industrial valves, pumps, rotating equipment, and earthmoving machinery.",
  },
  {
    icon: FlaskConical,
    title: "Process & Chemical Industries",
    body: "Multi-phase fluid transport, cyclones, chemical reactors, and industrial mixing vessels.",
  },
];


const blogPosts = [
  {
    title: "FSI Explained: When Flow Starts Breaking Structures",
    excerpt:
      "Acoustic- and flow-induced vibration, water hammer and valve slam — and how coupled simulation catches them early.",
    topics: ["Flow-induced vibration", "Water hammer / surge", "Valve closure loads"],
    image: `${IMG}/1.png`,
  },
  {
    title: "Conjugate Heat Transfer for Pressure Equipment",
    excerpt:
      "Tracking heat loss, thermal stratification and thermal shock in vessels, exchangers and piping.",
    topics: ["CHT modelling", "Thermal stratification", "Transient thermal stress"],
    image: `${IMG}/2.png`,
  },
  {
    title: "Multi-Phase & Cavitation Modelling in ANSYS Fluent",
    excerpt:
      "Liquid-gas interfaces, cavitation and slurry transport across pumps, valves and reactors.",
    topics: ["Free-surface flows", "Cavitation onset", "Slurry erosion"],
    image: `${IMG}/3.png`,
  },
  {
    title: "From CFD to Fatigue: Projecting Thermal Data onto FEA",
    excerpt:
      "Mapping fluid and thermal results onto structural models for creep-fatigue and life assessment.",
    topics: ["Thermal mapping", "Creep-fatigue interaction", "Remaining life"],
    image: `${IMG}/4.png`,
  },
  {
    title: "Multi-Body Dynamics as a Load Source for FEA",
    excerpt:
      "Extracting real operating-cycle accelerations and joint forces to drive accurate structural models.",
    topics: ["Dynamic load extraction", "Flexible-body MBD", "FEA integration"],
    image: `${IMG}/1.png`,
  },
  {
    title: "Coupled Electro-Thermal-Flow for EV & Power Electronics",
    excerpt:
      "Where current makes heat, heat changes cooling, and cooling changes the structure — solved together.",
    topics: ["Busbars & transformers", "Battery thermal management", "Powertrain cooling"],
    image: `${IMG}/2.png`,
  },
];

type Faq = { question: string; answer: string };

const faqs: Faq[] = [
  {
    question: "Why should our company outsource CFD and multi-physics simulation services to ProSIM?",
    answer:
      "Outsourcing your simulation requirements to our specialized team provides immediate access to premium software tools, such as ANSYS Fluent, and deep technical expertise without the overhead of an in-house department. We bring the necessary scale and rigorous analytical methods to accelerate your product development cycles, boost overall performance, and ensure your engineering initiatives remain strictly on schedule and budget.",
  },
  {
    question: "How does Fluid-Structure Interaction (FSI) analysis prevent costly piping and valve failures?",
    answer:
      "Equipment failures disrupt operations and impact your bottom line. We use advanced FSI modeling to examine the combined effects of fluid streams on component integrity. By accurately predicting acoustic-induced vibrations, water hammer effects, surge conditions, and the impact of sudden valve closures, we help you mitigate risks and avoid severe operational breakdowns before manufacturing begins.",
  },
  {
    question: "Do you provide Fitness-for-Service (FFS) and remaining life assessments for industrial equipment?",
    answer:
      "Yes. For industries operating high-pressure and high-temperature equipment, assessing asset longevity is critical for safety and capital planning. We integrate fluid dynamics with fracture mechanics to model the start and spread of structural cracks, evaluate high-temperature durability, and analyze fatigue. This allows us to confidently estimate your equipment's remaining useful life and establish highly secure operating boundaries.",
  },
  {
    question: "Can you optimize battery thermal management and cooling for EVs and electrical transformers?",
    answer:
      "Absolutely. Practical engineering challenges require a holistic approach. We utilize fully coupled Electro-Magnetic-Thermal-Structural-Flow analysis to model systems where electrical currents produce heat, which in turn alters cooling performance and causes structural expansion. This capability is essential for automotive, EV, and power generation clients looking to optimize the thermal management of complex powertrains and electrical enclosures.",
  },
  {
    question: "How do your CFD consultants conduct root cause analysis for recurring equipment failures?",
    answer:
      "We go far beyond delivering attractive visual plots; we convert fluid data into tangible structural outcomes. By leveraging advanced analytical techniques, our simulation experts diagnose hidden fluid-related issues — such as localized cavitation, flow-induced cracking, or severe thermal fatigue — to pinpoint the precise origins of recurring failures and recommend permanent, real-world engineering solutions.",
  },
  {
    question: "Are your engineering simulation reports compliant with ASME, API, and BS industry standards?",
    answer:
      "Yes, strict code compliance is built into our analytical framework. We seamlessly align our sophisticated fluid dynamics and structural simulation results with established international engineering codes, including ASME, API, and BS. This guarantees comprehensive design validation and ensures that your products seamlessly clear strict industry regulations.",
  },
  {
    question: "How can fluid flow optimization improve the efficiency of our process machinery and manifold networks?",
    answer:
      "Inefficient fluid flow leads to energy waste and excessive wear. Our flow optimization strategies pinpoint and eliminate dead zones, reduce unnecessary pressure drops, and streamline fluid pathways throughout intricate valves, ducts, and manifold networks. This translates to lower operating costs, enhanced system reliability, and maximized equipment efficiency.",
  },
  {
    question: "Do you have expertise in multi-phase flow simulations for chemical reactors and rotating equipment?",
    answer:
      "Yes, we serve the process, chemical, and heavy engineering sectors with industry-recognized simulations that accurately map complicated fluid behaviors. We routinely model liquid-gas boundaries, cavitation, slurry transport, and intricate mixing processes across rotating equipment, cyclones, and industrial reactors to guarantee operational precision.",
  },
  {
    question: "How do Multi-Body Dynamics (MBD) simulations validate the reliability of our moving assemblies?",
    answer:
      "Moving assemblies experience complex, real-world forces that static tests cannot capture. We calculate the precise, fluctuating accelerations, velocities, and joint forces experienced throughout standard operating cycles. By transferring these dynamic forces directly into subsequent fatigue and structural models, we achieve unparalleled physical accuracy, ensuring your assemblies can survive harsh operational demands.",
  },
  {
    question: "How does ProSIM's global delivery model for engineering simulation accelerate our project timelines?",
    answer:
      "Leveraging our Indian-based premium simulation services gives you a highly competitive advantage. Our seasoned fluid dynamics experts excel at translating intricate analytical data into practical engineering choices. This global delivery framework ensures rapid turnaround times, scalable engineering support, and cost-effective solutions for your most mission-critical and time-sensitive engineering projects.",
  },
];

export default function ComputationalFluidDynamics() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <main className="seismic-page">

      {/* PROJECTS */}
      <ProjectsHighlight />

      {/* FAQ */}
      <section className="sa-faq" id="faq-cfd-multiphysics">
        <div className="sa-container">
          <div className="sa-faq-heading">
            <span className="sa-label">FAQ&apos;s</span>

            <h2>CFD &amp; Multi-Physics FAQs</h2>
          </div>

          <div className="sa-faq-list">
            {faqs.map((faq, index) => {
              const isOpen = openFaq === index;

              return (
                <div
                  className={`sa-faq-item ${isOpen ? "active" : ""}`}
                  key={faq.question}
                >
                  <button
                    type="button"
                    className="sa-faq-question"
                    onClick={() => setOpenFaq(isOpen ? null : index)}
                    aria-expanded={isOpen}
                  >
                    <span className="sa-faq-number">
                      {String(index + 1).padStart(2, "0")}
                    </span>

                    <strong>{faq.question}</strong>

                    <span className="sa-faq-icon">
                      {isOpen ? (
                        <Minus size={19} strokeWidth={1.8} />
                      ) : (
                        <Plus size={19} strokeWidth={1.8} />
                      )}
                    </span>
                  </button>

                  <div className={`sa-faq-answer ${isOpen ? "show" : ""}`}>
                    <div>
                      <p>{faq.answer}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* BLOGS */}
      <section className="sa-blogs" id="blogs">
        <div className="sa-container">
          <span className="sa-label">Blog</span>
          <h2>Insights from Our Fluid Dynamics Desk</h2>
          <p className="sa-section-intro">
            Technical explainers and case notes on FSI, conjugate heat transfer,
            multi-phase flow, CFD-to-fatigue mapping, multi-body dynamics and
            coupled multiphysics.
          </p>
        </div>

        <div className="sa-blogs-marquee">
          <div className="sa-blogs-track">
            {[...blogPosts, ...blogPosts].map((post, index) => (
              <article
                className="sa-blog-card"
                key={index}
                aria-hidden={index >= blogPosts.length}
              >
                <div className="sa-blog-image">
                  <img src={post.image} alt={post.title} loading="lazy" />
                </div>
                <div className="sa-blog-body">
                  <h3>{post.title}</h3>
                  <p>{post.excerpt}</p>
                  <ul>
                    {post.topics.map((topic) => (
                      <li key={topic}>{topic}</li>
                    ))}
                  </ul>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
