"use client";

import React, { useState } from "react";
import Breadcrumbs from "@/app/Components/Breadcrumbs/Breadcrumbs";
import {
  ArrowUpRight,
  Cog,
  Wrench,
  Boxes,
  Building2,
  Zap,
  Plus,
  Minus,
} from "lucide-react";
import "./cfd.css";

const services = [
  {
    id: "cfd-fsi",
    title: "Computational Fluid Dynamics (CFD) & Fluid-Structure Interaction",
    icon: Cog,
    description:
      "By utilizing focused fluid dynamics analyses, we model intricate fluid movements to fine-tune thermal systems and accurately forecast how fluids in motion affect nearby physical structures. To produce highly dependable virtual prototypes, our specialists rely on premium software tools, particularly leveraging the advanced capabilities of the ANSYS Fluent platform.",
    points: [
      "Fluid-Structure Interaction (FSI): We examine the combined effects of fluid streams on component integrity. This is essential for assessing acoustic-induced and flow-induced vibrations, water hammer or surge conditions, and the impact of sudden valve closures within piping arrays.",
      "Multi-Phase & Free Surface Flows: Our industry-recognized simulations accurately map liquid-gas boundaries, cavitation, slurry movement, and mixing processes across rotating equipment and process machinery.",
      "Thermal & Conjugate Heat Transfer (CHT): We provide focused thermal evaluations to track complicated heat loss and dissipation. This includes monitoring thermal stratification inside pipes and analyzing thermal shocks affecting pressure vessels and heat exchangers.",
      "Flow Optimization: Our approaches reduce unnecessary pressure drops, clear out dead zones, and streamline fluid pathways throughout intricate valves, ducts, and manifold networks.",
    ],
    images: [
      {
        src: "/new-img/offerings/CFD/1.png",
        alt: "Seismic Analysis",
      },
      {
        src: "/new-img/offerings/CFD/2.png",
        alt: "Seismic Analysis",
      },
    ],
  },
  {
    id: "damage-modeling",
    title: "Materials, Damage Modeling & Life Assessment",
    icon: Wrench,
    description:
      "Moving past basic linear evaluations, we investigate how severe mechanical and thermal stresses deteriorate materials throughout their operational lifespan. By integrating these insights with our fluid dynamics analyses, we seamlessly project complicated thermal data onto comprehensive structural frameworks.",
    points: [
      "High-Temperature Durability: We analyze fatigue, creep, and their combined interactions within high-pressure, high-temperature equipment. Typical assets evaluated include industrial reactors, steam turbines, and power plant piping assemblies.",
      "Fracture Mechanics & Fitness-for-Service (FFS): By modeling both the start and subsequent spread of structural cracks, we confidently estimate an asset's remaining useful life and establish secure operating boundaries.",
    ],
  },
  {
    id: "mbd-analysis",
    title: "Multi-Body Dynamics (MBD)",
    icon: Boxes,
    description:
      "We determine the actual dynamic and kinematic responses of intricate, linked assemblies comprising both flexible and rigid parts. When paired with the robust outputs of our ANSYS Fluent workflows, these dynamic simulations effectively incorporate real-world forces generated by fluid motion.",
    points: [
      "Dynamic Load Extraction: We calculate accurate, fluctuating accelerations, velocities, and joint forces experienced throughout standard operating cycles.",
      "FEA Integration: By transferring these precise dynamic forces directly into subsequent fatigue and structural models, we achieve unparalleled levels of physical accuracy.",
    ],
    images: [
      {
        src: "/new-img/offerings/CFD/3.png",
        alt: "Seismic Analysis",
      },
      {
        src: "/new-img/offerings/CFD/4.png",
        alt: "Seismic Analysis",
      },
    ],
  },
  {
    id: "coupled-multiphysics",
    title: "Fully Coupled Multiphysics Analysis",
    icon: Building2,
    description:
      "Because practical engineering challenges seldom occur in a vacuum, we connect separate physical disciplines using simultaneous, multi-directional coupling. This advanced approach is heavily supported by our foundational fluid dynamics capabilities.",
    points: [
      "Electro-Magnetic-Thermal-Structural-Flow Coupling: We model interconnected systems where electrical currents produce heat, which in turn alters cooling performance and triggers structural expansion. Typical applications include busbars, electrical transformers, and electric vehicle powertrains. Here, our comprehensive fluid simulations are essential for assessing and optimizing the overall thermal management of these complex setups.",
    ],
  },
  {
    id: "industries-served",
    title: "Industries & Verticals We Serve",
    icon: Zap,
    description:
      "Because our premium fluid dynamics and multi-physics capabilities transcend specific markets, we consistently provide highly detailed engineering insights to a wide array of industrial sectors.",
    points: [
      "Oil & Gas, Petrochemicals & Refineries: We evaluate offshore platforms, subsea hardware, storage tanks, pressure vessels, and complicated piping infrastructure.",
      "Power Generation (Thermal, Nuclear, Renewables): Our teams analyze high-energy piping, heat exchangers, gas and steam turbines, and boiler headers.",
      "Automotive & Electric Vehicles (EV): We assess structural resilience, motor cooling mechanisms, battery thermal management, and overall powertrain dynamics.",
      "Aerospace & Defense: Our expertise covers high-velocity impacts, defense payloads, turbomachinery, and specialized aerodynamic components.",
      "Heavy Engineering & Industrial Machinery: We support the development of heavy cranes, industrial valves, pumps, rotating equipment, and earthmoving machinery.",
      "Process & Chemical Industries: We simulate multi-phase fluid transport, cyclones, chemical reactors, and industrial mixing vessels.",
    ],
  },
];

const advantages = [
  {
    number: "01",
    icon: Cog,
    title: "Cross-Domain Expertise",
    text: "Rather than simply delivering attractive visual plots, we convert fluid data into tangible structural outcomes. This ensures that your vessels, piping, and pumps are fully capable of surviving harsh operational demands.",
  },
  {
    number: "02",
    icon: Wrench,
    title: "Root Cause Analysis",
    text: "We identify the precise origins of recurring equipment failures, from flow-induced cracking and localized cavitation to severe thermal fatigue. Leveraging advanced ANSYS Fluent techniques allows us to correctly diagnose these hidden fluid-related issues.",
  },
  {
    number: "03",
    icon: Boxes,
    title: "Code Compliance",
    text: "We seamlessly align our sophisticated simulation results with established international standards, including BS, API, and ASME, guaranteeing comprehensive design validation.",
  },
];

const faqs = [
  {
    question: "What computational fluid dynamics (CFD) services does ProSIM provide?",
    answer:
      "ProSIM provides cutting-edge multi-physics simulations and computational fluid dynamics solutions, building on an established finite element analysis foundation. Our expertise lies in unraveling complicated thermal-fluid dynamics alongside intricate structural interactions using platforms like ANSYS Fluent.",
  },
  {
    question: "What is Fluid-Structure Interaction (FSI) and how is it applied?",
    answer:
      "We examine the combined effects of fluid streams on component integrity. This is essential for assessing acoustic-induced and flow-induced vibrations, water hammer or surge conditions, and the impact of sudden valve closures within piping arrays.",
  },
  {
    question: "What capabilities do you offer in multi-phase and free surface flows?",
    answer:
      "Our industry-recognized simulations accurately map liquid-gas boundaries, cavitation, slurry movement, and mixing processes across rotating equipment and process machinery.",
  },
  {
    question: "How do you evaluate thermal performance and heat transfer?",
    answer:
      "We provide focused thermal evaluations to track complicated heat loss and dissipation, including monitoring thermal stratification inside pipes and analyzing thermal shocks affecting pressure vessels and heat exchangers.",
  },
  {
    question: "What is involved in Materials, Damage Modeling & Life Assessment?",
    answer:
      "We investigate how severe mechanical and thermal stresses deteriorate materials throughout their operational lifespan, analyzing high-temperature durability (fatigue, creep) and conducting fracture mechanics and Fitness-for-Service (FFS) reviews.",
  },
  {
    question: "How does Multi-Body Dynamics (MBD) integrate with fluid workflows?",
    answer:
      "We determine dynamic and kinematic responses of intricate assemblies. When paired with ANSYS Fluent workflows, these simulations incorporate real-world forces generated by fluid motion to extract dynamic loads and feed precise forces into FEA models.",
  },
  {
    question: "What is Fully Coupled Multiphysics Analysis?",
    answer:
      "We connect separate physical disciplines using simultaneous, multi-directional coupling, such as Electro-Magnetic-Thermal-Structural-Flow Coupling for busbars, electrical transformers, and electric vehicle powertrains.",
  },
  {
    question: "Which industries do you serve for CFD and multi-physics simulations?",
    answer:
      "We serve Oil & Gas, Petrochemicals & Refineries, Power Generation, Automotive & Electric Vehicles (EV), Aerospace & Defense, Heavy Engineering & Industrial Machinery, and Process & Chemical Industries.",
  },
  {
    question: "What are the advantages of partnering with ProSIM for CFD?",
    answer:
      "Organizations benefit from our cross-domain expertise converting fluid data into structural outcomes, root cause analysis for equipment failures using ANSYS Fluent, and strict alignment with international codes like BS, API, and ASME.",
  },
];

const navigationItems = [
  {
    title: "CFD & FSI",
    id: "cfd-fsi",
    icon: Cog,
  },
  {
    title: "Damage & Life Assessment",
    id: "damage-modeling",
    icon: Wrench,
  },
  {
    title: "Multi-Body Dynamics",
    id: "mbd-analysis",
    icon: Boxes,
  },
  {
    title: "Coupled Multiphysics",
    id: "coupled-multiphysics",
    icon: Building2,
  },
  {
    title: "Industries Served",
    id: "industries-served",
    icon: Zap,
  },
];

export default function CFDPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setOpenFaq((current) => (current === index ? null : index));
  };

  return (
    <main className="seismic-page">
      <Breadcrumbs />

      {/* HERO */}
      <section className="sa-hero">
        <div className="sa-container">
        
          <h1>CFD & Multi-Physics Simulation Services</h1>

          <p>
            Building on our established finite element analysis foundation, ProSIM provides cutting-edge multi-physics simulations and computational fluid dynamics solutions. As a leading provider in the simulation space, our expertise lies in unraveling complicated thermal-fluid dynamics alongside intricate structural interactions.
          </p>

          <p>
            By leveraging our specialized engineering support, industrial clients can successfully boost product performance, meet strict industry regulations, and effectively avoid severe operational breakdowns. For companies seeking to accelerate their development cycles by outsourcing these simulations, we bring the necessary scale, deep technical knowledge, and rigorous analytical methods demanded by mission-critical engineering initiatives.
          </p>
        </div>
      </section>

      {/* NAVIGATION */}
      <section className="sa-navigation">
        <div className="sa-container">
          <div className="sa-navigation-card">
            <h2>CFD & Multi-Physics Simulation Services</h2>

            <div className="sa-navigation-grid">
              {navigationItems.map((item) => {
                const Icon = item.icon;

                return (
                  <a
                    href={`#${item.id}`}
                    className="sa-navigation-link"
                    key={item.id}
                  >
                    <div className="sa-navigation-item">
                      <div className="sa-navigation-icon">
                        <Icon size={25} strokeWidth={1.8} />
                      </div>

                      <h3>{item.title}</h3>

                      <span>
                        <ArrowUpRight size={20} strokeWidth={1.8} />
                      </span>
                    </div>
                  </a>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* INTRO */}
      <section className="sa-intro">
        <div className="sa-container">
          <span className="sa-label">OUR EXPERTISE</span>

          <h2>Specialized, Multidisciplinary Engineering Solutions</h2>

          <p>
            We offer a broad range of specialized, multidisciplinary engineering solutions, spanning from foundational flow evaluations to sophisticated multi-phase configurations and fully coupled multiphysics.
          </p>
        </div>
      </section>

      {/* SERVICES */}
      <section className="sa-services">
        <div className="sa-container">
          <div className="sa-service-list">
            {services.map((service, index) => {
              const Icon = service.icon;

              return (
                <article
                  className="sa-service-box"
                  id={service.id}
                  key={service.id}
                >
                  <div className="sa-service-top">
                    <div className="sa-service-number">
                      <span>{String(index + 1).padStart(2, "0")}</span>

                      <div className="sa-service-icon">
                        <Icon size={24} strokeWidth={1.8} />
                      </div>
                    </div>

                    <ArrowUpRight
                      className="sa-service-arrow"
                      size={25}
                      strokeWidth={1.8}
                    />
                  </div>

                  <h2>{service.title}</h2>

                  <p>{service.description}</p>

                  <ul>
                    {service.points.map((point) => (
                      <li key={point}>{point}</li>
                    ))}
                  </ul>

                  {service.images && (
                    <div
                      className={`sa-gallery ${
                        service.images.length === 1 ? "single" : ""
                      }`}
                    >
                      {service.images.map((image) => (
                        <div className="sa-gallery-card" key={image.src}>
                          <img src={image.src} alt={image.alt} />
                        </div>
                      ))}
                    </div>
                  )}
                </article>
              );
            })}
          </div>
        </div>
      </section>

      {/* ADVANTAGE */}
      <section className="sa-advantage">
        <div className="sa-container">
          <span className="sa-label">WHY PROSIM</span>

          <h2>Why Partner with ProSIM?</h2>

          <p className="sa-section-intro">
            Organizations seeking reliable fluid dynamics analysis benefit from several unique advantages when partnering with ProSIM.
          </p>

          <div className="sa-advantage-list">
            {advantages.map((item) => {
              const Icon = item.icon;

              return (
                <div className="sa-advantage-box" key={item.number}>
                  <span className="sa-advantage-number">{item.number}</span>

                  <div className="sa-advantage-icon">
                    <Icon size={22} strokeWidth={1.8} />
                  </div>

                  <div className="sa-advantage-content">
                    <h3>{item.title}</h3>
                    <p>{item.text}</p>
                  </div>

                  <ArrowUpRight size={23} strokeWidth={1.8} />
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="sa-faq" id="faq-cfd-multiphysics">
        <div className="sa-container">
          <div className="sa-faq-heading">
            <span className="sa-label">FAQ</span>

            <h2>Frequently Asked Questions</h2>

            <p>
              Find answers to common questions about our CFD and multi-physics simulation services.
            </p>
          </div>

          <div className="sa-faq-list">
            {faqs.map((faq, index) => {
              const isOpen = openFaq === index;

              return (
                <div
                  className={`sa-faq-item ${isOpen ? "active" : ""}`}
                  key={faq.question}
                >
                  <button
                    type="button"
                    className="sa-faq-question"
                    onClick={() => toggleFaq(index)}
                    aria-expanded={isOpen}
                    aria-controls={`cfd-faq-answer-${index}`}
                  >
                    <span className="sa-faq-number">
                      {String(index + 1).padStart(2, "0")}
                    </span>

                    <strong>{faq.question}</strong>

                    <span className="sa-faq-icon">
                      {isOpen ? (
                        <Minus size={19} strokeWidth={1.8} />
                      ) : (
                        <Plus size={19} strokeWidth={1.8} />
                      )}
                    </span>
                  </button>

                  <div
                    id={`cfd-faq-answer-${index}`}
                    className={`sa-faq-answer ${isOpen ? "show" : ""}`}
                    aria-hidden={!isOpen}
                  >
                    <div>
                      <p>{faq.answer}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </main>
  );
}